# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.ssh.insert_key = false
  config.ssh.paranoid = false
  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.network "private_network", ip: "192.168.33.10"
    node1.vm.network "private_network", ip: "192.168.44.10"
  end
  config.vm.define "node2" do |node2|
    node2.vm.box = "centos/7"
    node2.vm.network "private_network", ip: "192.168.33.11"
    node2.vm.network "private_network", ip: "192.168.44.11"
  end

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
  end
end
